version: '3.1'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/hosts:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./../public:/var/www/html/public
    links:
      - php
  php:
    build: ./php
    volumes:
      - ./../:/var/www/html
